### ISSUE TITLE
Where is the tutorial ?

### ISSUE THREAD

**Issue by Learnerhua** [SegataLab/lefse#15]
I am a green hand, so I don't know how to start with this program, What should I do ? Where can  I find the tutorial for this program?
THANK YOU

**Comment by marwa38** [comment]
I just found out this one 
https://ycl6.github.io/16S-Demo/3_lefse_tutorial.html

**Comment by Learnerhua** [comment]
I found a better one today.

Sharing with you !

https://github.com/biobakery/biobakery/wiki/lefse#2-lefse--conda-docker-vm-
















At 2022-03-08 21:17:31, "marwa38" ***@***.***> wrote:

I just found out this one
https://ycl6.github.io/16S-Demo/3_lefse_tutorial.html

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by marwa38** [comment]
Thanks for sharing :)

**Comment by marwa38** [comment]
I think one issue is with transforming phyloseq object into the lefse input 
how you made that? incase you are with working with phyloseq 

https://rdrr.io/github/yiluheihei/microbiomeMarker/man/run_lefse.html
if not I will go for this, as it can have phyloseq object
Kind regards 
Marwa

**Comment by Learnerhua** [comment]
> 

Sorry, I have no idea for this, I am just a green hand.
Maybe you can ask someone related to your field.
