### ISSUE TITLE
Error in OTU without subclass and subject

### ISSUE THREAD

**Issue by benben-miao** [SegataLab/lefse#4]
`python3 format_input.py input.txt output.in`

```python
Traceback (most recent call last):
  File "format_input.py", line 453, in <module>
    class_sl,subclass_sl,class_hierarchy = get_class_slices(list(zip(cls['class'], cls['subclass'], cls['subject'])))
KeyError: 'subject'
```

**Comment by fbeghini** [comment]
Hi, can you provided the input file?

**Comment by Wellington9023** [comment]
![image](https://user-images.githubusercontent.com/38586413/102212118-9e6dfe00-3f0f-11eb-9fdc-bc4dc5e019b2.png)
[hmp_aerobiosis_small.txt](https://github.com/SegataLab/lefse/files/5695598/hmp_aerobiosis_small.txt)
I have a same problem,hoping for help, thank you !

**Comment by wolvesled** [comment]
@fbeghini I'm using the latest v1.1.2, and still have this problem, I tested with the example input file provided by the guide:

```python
$ lefse_format_input.py hmp_aerobiosis_small.txt hmp_aerobiosis_small.in -c 1 -o 1000000
Traceback (most recent call last):
  File "/home/agean/anaconda3/envs/lefse1.1.2/bin/lefse_format_input.py", line 10, in <module>
    sys.exit(format_input())
  File "/home/agean/anaconda3/envs/lefse1.1.2/lib/python3.10/site-packages/lefse/lefse_format_input.py", line 437, in format_input
    class_sl,subclass_sl,class_hierarchy = get_class_slices(list(zip(cls['class'], cls['subclass'], cls['subject'])))
KeyError: 'subject'
```

Note I remove the `-s` and `-u` options, it should fall back to the default value as I saw in the code, but it won't work, even if I specify `-s -1 -u -1` the result is the same.

**Comment by baishengjun** [comment]
Encounter the same problem, but it works with example data

**Comment by Gandziek** [comment]
If someone is using conda installation there is an old version of  lefse_format_input.py script. The new one that is available on github is working so all you need to do is change the script in your conda directory (in this case: /home/agean/anaconda3/envs/lefse1.1.2/lib/python3.10/site-packages/lefse/lefse_format_input.py).
