### ISSUE TITLE
Python 3 or 2.7?

### ISSUE THREAD

**Issue by chlige** [SegataLab/lefse#5]
The scripts on GitHub seem to indicate that LEfSE should use python3.  However, when I try to install via conda, I have see the following error.

<pre>
UnsatisfiableError: The following specifications were found to be in conflict:
  - lefse -> python[version='>=2.7,<2.8.0a0']
  - python=3
</pre>

There also seem to be issues with the docker image.  I have tried to run "plot_cladogram.py" within the biobakery/lefse image and receive the following error message.

<pre>
Traceback (most recent call last):
  File "/export/local_tools/lefse/plot_cladogram.py", line 3, in <module>
    import os,sys,matplotlib,argparse,string
ImportError: No module named matplotlib
</pre>

Any help would be greatly appreciated!

Thanks!

**Comment by fbeghini** [comment]
The bioconda recipe seems to be broken, have you tried installing it using
pip from the repository?
----
*Francesco Beghini*
*PhD Student*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy

ᐧ

**Comment by ctekellogg** [comment]
Hi, I am also running into this problem and cannot install lefse via conda `conda install -c biobakery lefse`

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - lefse -> python[version='2.7.*|<3|>=2.7,<2.8.0a0']

Your python: python=3.7
```

**Comment by fquerdasi** [comment]
Hi, I'm wondering if there have been any updates since this original comment was posted regarding the error in python versions when installing via conda? Is it possible to install LEfSE somehow using python 3?
